### PR TITLE
Fix some problem with installer from update nuget

### PR DESCRIPTION
**Pull request by chuongmep**
Some problem fix : 
- [x] Show message box not correct
- [x] Add file menu
- [x] Support F12 to goto data binding
- [x] Fix file Installer from nuget update

### CODE REVIEW

**Comment by sridharbaldava** [comment]
Thanks for opening this PR. I will review and merge when I am back from holidays.

**Comment by sridharbaldava** [comment]
I am trying to understand the motivation/benefit to using messagebox instead of task dialog and returning the error message back to Revit API. Rest of it looks ok.

**Comment by chuongmep** [comment]
Oh, actually, i see a problem mistake between title with content message to show. ToString will be show error clearly message for debug.

**Comment by sridharbaldava** [comment]
OK, I see. Can you edit to leave the taskdialog in and only change the message contents to .ToString() instead of ex.Message.
TaskDialog.Show("Error", ex.ToString());

**Comment by chuongmep** [comment]
@sridharbaldava changed.

**Pull request merged**
